#!/bin/bash
label=$1
location=$2
CONFIG=$(echo $* | sed 's/.\+config=\(.\+\)/\1/')
USER=$(basename ${CONFIG%.gdfuse*})
FUSE=$(echo $* | sed 's/.\+-o \(.\+\),config=.\+/\1/')
sudo -u $USER /usr/bin/google-drive-ocamlfuse -config $CONFIG -label $label $location -o $FUSE
exit 0
