#!/bin/bash
# Set MOOSE_JOBS to the number of physical processors available
export MOOSE_JOBS=`cat /proc/cpuinfo | grep processor | wc -l`

# Modules Source
source /opt/moose/Modules/3.2.10/init/bash

# MOOSE_PPS_WIDTH
export MOOSE_PPS_WIDTH=180

# Load the moose-tools module by default:
module load moose-tools
export PETSC_DIR='/usr/lib/petsc'
