#!/bin/bash

# Create dockeruser homedir
mkdir -p /home/dockeruser

# Set UID/PID of user that youtube-dl will be run as
TVNAMERPGID=${PGID:-1000}
TVNAMERPUID=${PUID:-1000}

# Check to see if group/user already exist, if so, delete
EXISTINGGROUPNAME=$(getent group "$TVNAMERPGID" | cut -d ':' -f 1)
EXISTINGUSERNAME=$(getent passwd "$TVNAMERPUID" | cut -d ':' -f 1)
if [[ -n "$EXISTINGGROUPNAME" ]]; then
    groupdel -f "$EXISTINGGROUPNAME"
fi
if [[ -n "$EXISTINGUSERNAME" ]]; then
    userdel -f "$EXISTINGUSERNAME"
fi

# Create user/group
addgroup --quiet --gid "$TVNAMERPGID" dockeruser
chown -R "$TVNAMERPUID":"$TVNAMERPGID" /home/dockeruser
adduser --quiet --system --disabled-password --uid "$TVNAMERPUID" --gid "$TVNAMERPGID" --home /home/dockeruser dockeruser
HOME=/home/dockeruser
export HOME

# Set UMASK if required
if [[ -n "$UMASK" ]]; then
    umask "$UMASK"
fi

# Run tvnamer with remainder of command line arguments
if [ -f /config/tvnamerconfig.json ]; then
  setpriv --reuid dockeruser --regid dockeruser --keep-groups tvnamer -c /config/tvnamerconfig.json "$@"
else
  setpriv --reuid dockeruser --regid dockeruser --keep-groups tvnamer "$@"
fi
