name: "test-install-dev"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  GREEN: '\033[0;32m'
  NC: '\033[0m'
jobs:
  devcontainer:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
    env:
      DEV_WORKSPACE: "/workspace"
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install
        run: ./install.sh
