name: "test-install"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest 
    container:
      image: archlinux:latest
      volumes: 
        - ${{ github.workspace }}:/root/dotfiles
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: install
        run: |
          yes | pacman -S git && \
          git config --global --add safe.directory $HOME/dotfiles && \
          cd $HOME/dotfiles && \
          ./install.sh
