name: "test-install"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  install:
    container:
      image: archlinux:latest
      options: --user=root --entrypoint=/bin/bash
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_AUTH_SOCK: ${{ secrets.SSH_AUTH_SOCK }}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${{ github.workspace }}:/workspace
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup ssh
        uses: PhutureCorp/container-ssh-agent@v0.0.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: install
        run: |
          pacman -Sy --noconfirm sudo openssh git 
          git config --global --add safe.directory /workspace
          cd /workspace
          ./install.sh"
